### ISSUE TITLE
Temp file not flushed before read by wkhtmltopdf 

### ISSUE THREAD

**Issue by ncjones** [openlabs/docker-wkhtmltopdf-aas#5]
The temp file used to store the posted source HTML is not flushed before being read by the wkhtmltopdf process. This results in an incomplete view of the uploaded HTML file being rendered. In the case of small files it always results in an empty PDF being generated.

For example, the following command will unexpectedly produce an empty PDF document (assuming app listening on port 8090):

    $ echo '<html><body><h1>Hello World!</h1></body></html>' \
      | curl -X POST -F file=@- http://localhost:8090/ > output.pdf

**Comment by sharoonthomas** [comment]
@ncjones just saw your PR. Merged it.

Thanks for the patch. :+1:

**Comment by ncjones** [comment]
@sharoonthomas FYI, you may want to look at pulling in the other changes from my fork including
* No File I/O - files are passed to/from the child process via pipes instead of temp files 
* a performance test suite using Locust - by tweaking number of gunicorn workers, throughput varies between 5 and 50 messages per second on my laptop.

See https://github.com/ncjones/html-pdf-webservice

**Comment by sharoonthomas** [comment]
@ncjones those changes look very interesting. any particular reason why you preferred to remove the JSON api ? do you have better ideas on sending options ?

**Comment by ncjones** [comment]
It was not needed for my usecase so I dropped it. I would use HTTP headers for providing rendering parameters.
